# frozen_string_literal: true

# The Simple Darwin Core terms, each with the label and the class the TDWG
# standard gives it. Data, not logic: generated from TDWG's
# vocabulary/term_versions.csv (recommended terms) and
# dist/simple_dwc_vertical.csv. See docs/metadata-records.md for how to
# regenerate it.
module DarwinCoreTerms
  # The display order of the classes, and each one's heading. Record-level
  # terms carry no class in the standard.
  GROUPS = {
    record:             'Record-level',
    occurrence:         'Occurrence',
    organism:           'Organism',
    material_entity:    'Material Entity',
    material_sample:    'Material Sample',
    event:              'Event',
    location:           'Location',
    geological_context: 'Geological Context',
    identification:     'Identification',
    taxon:              'Taxon'
  }.freeze

  # [term, label, group], in the order simple_dwc_vertical.csv lists them.
  TERMS = [
    ['type',                                'Type',                                          :record],
    ['modified',                            'Date Modified',                                 :record],
    ['language',                            'Language',                                      :record],
    ['license',                             'License',                                       :record],
    ['rightsHolder',                        'Rights Holder',                                 :record],
    ['accessRights',                        'Access Rights',                                 :record],
    ['bibliographicCitation',               'Bibliographic Citation',                        :record],
    ['references',                          'References',                                    :record],
    ['feedbackURL',                         'Feedback URL',                                  :record],
    ['institutionID',                       'Institution ID',                                :record],
    ['collectionID',                        'Collection ID',                                 :record],
    ['datasetID',                           'Dataset ID',                                    :record],
    ['institutionCode',                     'Institution Code',                              :record],
    ['collectionCode',                      'Collection Code',                               :record],
    ['ownerInstitutionCode',                'Owner Institution Code',                        :record],
    ['datasetName',                         'Dataset Name',                                  :record],
    ['basisOfRecord',                       'Basis Of Record',                               :record],
    ['informationWithheld',                 'Information Withheld',                          :record],
    ['dataGeneralizations',                 'Data Generalizations',                          :record],
    ['dynamicProperties',                   'Dynamic Properties',                            :record],
    ['eventID',                             'Event ID',                                      :event],
    ['parentEventID',                       'Parent Event ID',                               :event],
    ['eventCategory',                       'Event Category',                                :event],
    ['eventType',                           'Event Type',                                    :event],
    ['fieldNumber',                         'Field Number',                                  :event],
    ['eventDate',                           'Event Date',                                    :event],
    ['eventTime',                           'Event Time',                                    :event],
    ['startDayOfYear',                      'Start Day Of Year',                             :event],
    ['endDayOfYear',                        'End Day Of Year',                               :event],
    ['year',                                'Year',                                          :event],
    ['month',                               'Month',                                         :event],
    ['day',                                 'Day',                                           :event],
    ['verbatimEventDate',                   'Verbatim EventDate',                            :event],
    ['habitat',                             'Habitat',                                       :event],
    ['sampledSubstrateCategory',            'Sampled Substrate Category',                    :event],
    ['sampledSubstrateLayer',               'Sampled Substrate Layer',                       :event],
    ['samplingProtocol',                    'Sampling Protocol',                             :event],
    ['sampleSizeValue',                     'Sample Size Value',                             :event],
    ['sampleSizeUnit',                      'Sample Size Unit',                              :event],
    ['samplingEffort',                      'Sampling Effort',                               :event],
    ['fieldNotes',                          'Field Notes',                                   :event],
    ['eventRemarks',                        'Event Remarks',                                 :event],
    ['locationID',                          'Location ID',                                   :location],
    ['siteNumber',                          'Site Number',                                   :location],
    ['higherGeographyID',                   'Higher Geography ID',                           :location],
    ['higherGeography',                     'Higher Geography',                              :location],
    ['continent',                           'Continent',                                     :location],
    ['waterBody',                           'Water Body',                                    :location],
    ['islandGroup',                         'Island Group',                                  :location],
    ['island',                              'Island',                                        :location],
    ['country',                             'Country',                                       :location],
    ['countryCode',                         'Country Code',                                  :location],
    ['stateProvince',                       'First Order Division',                          :location],
    ['county',                              'Second Order Division',                         :location],
    ['municipality',                        'Third Order Division',                          :location],
    ['locality',                            'Locality',                                      :location],
    ['verbatimLocality',                    'Verbatim Locality',                             :location],
    ['minimumElevationInMeters',            'Minimum Elevation In Meters',                   :location],
    ['maximumElevationInMeters',            'Maximum Elevation In Meters',                   :location],
    ['verbatimElevation',                   'Verbatim Elevation',                            :location],
    ['verticalDatum',                       'Vertical Datum',                                :location],
    ['minimumDepthInMeters',                'Minimum Depth In Meters',                       :location],
    ['maximumDepthInMeters',                'Maximum Depth In Meters',                       :location],
    ['verbatimDepth',                       'Verbatim Depth',                                :location],
    ['minimumDistanceAboveSurfaceInMeters', 'Minimum Distance Above Surface In Meters',      :location],
    ['maximumDistanceAboveSurfaceInMeters', 'Maximum Distance Above Surface In Meters',      :location],
    ['locationAccordingTo',                 'Location According To',                         :location],
    ['locationRemarks',                     'Location Remarks',                              :location],
    ['preferredSpatialRepresentation',      'Preferred Spatial Representation',              :location],
    ['decimalLatitude',                     'Decimal Latitude',                              :location],
    ['decimalLongitude',                    'Decimal Longitude',                             :location],
    ['geodeticDatum',                       'Geodetic Datum',                                :location],
    ['coordinateUncertaintyInMeters',       'Coordinate Uncertainty In Meters',              :location],
    ['coordinatePrecision',                 'Coordinate Precision',                          :location],
    ['pointRadiusSpatialFit',               'Point Radius Spatial Fit',                      :location],
    ['verbatimCoordinates',                 'Verbatim Coordinates',                          :location],
    ['verbatimLatitude',                    'Verbatim Latitude',                             :location],
    ['verbatimLongitude',                   'Verbatim Longitude',                            :location],
    ['verbatimCoordinateSystem',            'Verbatim Coordinate System',                    :location],
    ['verbatimSRS',                         'Verbatim SRS',                                  :location],
    ['footprintWKT',                        'Footprint WKT',                                 :location],
    ['footprintSRS',                        'Footprint SRS',                                 :location],
    ['footprintSpatialFit',                 'Footprint Spatial Fit',                         :location],
    ['georeferencedBy',                     'Georeferenced By',                              :location],
    ['georeferencedDate',                   'Georeferenced Date',                            :location],
    ['georeferenceProtocol',                'Georeference Protocol',                         :location],
    ['georeferenceSources',                 'Georeference Sources',                          :location],
    ['georeferenceRemarks',                 'Georeference Remarks',                          :location],
    ['geologicalContextID',                 'Geological Context ID',                         :geological_context],
    ['earliestEonOrLowestEonothem',         'Earliest Eon Or Lowest Eonothem',               :geological_context],
    ['latestEonOrHighestEonothem',          'Latest Eon Or Highest Eonothem',                :geological_context],
    ['earliestEraOrLowestErathem',          'Earliest Era Or Lowest Erathem',                :geological_context],
    ['latestEraOrHighestErathem',           'Latest Era Or Highest Erathem',                 :geological_context],
    ['earliestPeriodOrLowestSystem',        'Earliest Period Or Lowest System',              :geological_context],
    ['latestPeriodOrHighestSystem',         'Latest Period Or Highest System',               :geological_context],
    ['earliestEpochOrLowestSeries',         'Earliest Epoch Or Lowest Series',               :geological_context],
    ['latestEpochOrHighestSeries',          'Latest Epoch Or Highest Series',                :geological_context],
    ['earliestAgeOrLowestStage',            'Earliest Age Or Lowest Stage',                  :geological_context],
    ['latestAgeOrHighestStage',             'Latest Age Or Highest Stage',                   :geological_context],
    ['lowestBiostratigraphicZone',          'Lowest Biostratigraphic Zone',                  :geological_context],
    ['highestBiostratigraphicZone',         'Highest Biostratigraphic Zone',                 :geological_context],
    ['lithostratigraphicTerms',             'Lithostratigraphic Terms',                      :geological_context],
    ['group',                               'Group',                                         :geological_context],
    ['formation',                           'Formation',                                     :geological_context],
    ['member',                              'Member',                                        :geological_context],
    ['bed',                                 'Bed',                                           :geological_context],
    ['identificationID',                    'Identification ID',                             :identification],
    ['identificationType',                  'Identification Type',                           :identification],
    ['verbatimIdentification',              'Verbatim Identification',                       :identification],
    ['isAcceptedIdentification',            'Is Accepted Identification',                    :identification],
    ['taxonFormula',                        'Taxon Formula',                                 :identification],
    ['identificationQualifier',             'Identification Qualifier',                      :identification],
    ['typeStatus',                          'Type Status',                                   :identification],
    ['identifiedBy',                        'Identified By',                                 :identification],
    ['identifiedByID',                      'Identified By ID',                              :identification],
    ['dateIdentified',                      'Date Identified',                               :identification],
    ['identificationReferences',            'Identification References',                     :identification],
    ['identificationVerificationStatus',    'Identification Verification Status',            :identification],
    ['identificationRemarks',               'Identification Remarks',                        :identification],
    ['materialEntityID',                    'Material Entity ID',                            :material_entity],
    ['digitalSpecimenID',                   'Digital Specimen ID',                           :material_entity],
    ['materialEntityCategory',              'Material Entity Category',                      :material_entity],
    ['materialEntityType',                  'Material Entity Type',                          :material_entity],
    ['discipline',                          'Discipline',                                    :material_entity],
    ['typeOfType',                          'Type Of Type',                                  :material_entity],
    ['typifiedName',                        'Typified Name',                                 :material_entity],
    ['catalogNumber',                       'Catalog Number',                                :material_entity],
    ['otherCatalogNumbers',                 'Other Catalog Numbers',                         :material_entity],
    ['recordNumber',                        'Record Number',                                 :occurrence],
    ['objectQuantity',                      'Object Quantity',                               :material_entity],
    ['objectQuantityType',                  'Object Quantity Type',                          :material_entity],
    ['preparations',                        'Preparations',                                  :material_entity],
    ['disposition',                         'Disposition',                                   :material_entity],
    ['verbatimLabel',                       'Verbatim Label',                                :material_entity],
    ['associatedSequences',                 'Associated Sequences',                          :material_entity],
    ['materialEntityRemarks',               'Material Entity Remarks',                       :material_entity],
    ['materialSampleID',                    'Material Sample ID',                            :material_sample],
    ['occurrenceID',                        'Occurrence ID',                                 :occurrence],
    ['recordedBy',                          'Recorded By',                                   :occurrence],
    ['recordedByID',                        'Recorded By ID',                                :occurrence],
    ['individualCount',                     'Individual Count',                              :occurrence],
    ['organismQuantity',                    'Organism Quantity',                             :occurrence],
    ['organismQuantityType',                'Organism Quantity Type',                        :occurrence],
    ['sex',                                 'Sex',                                           :occurrence],
    ['lifeStage',                           'Life Stage',                                    :occurrence],
    ['reproductiveCondition',               'Reproductive Condition',                        :occurrence],
    ['caste',                               'Caste',                                         :occurrence],
    ['behavior',                            'Behavior',                                      :occurrence],
    ['vitality',                            'Vitality',                                      :occurrence],
    ['establishmentMeans',                  'Establishment Means',                           :occurrence],
    ['degreeOfEstablishment',               'Degree of Establishment',                       :occurrence],
    ['pathway',                             'Pathway',                                       :occurrence],
    ['georeferenceVerificationStatus',      'Georeference Verification Status',              :occurrence],
    ['occurrenceStatus',                    'Occurrence Status',                             :occurrence],
    ['associatedMedia',                     'Associated Media',                              :occurrence],
    ['associatedOccurrences',               'Associated Occurrences',                        :occurrence],
    ['associatedReferences',                'Associated References',                         :occurrence],
    ['associatedTaxa',                      'Associated Taxa',                               :occurrence],
    ['occurrenceRemarks',                   'Occurrence Remarks',                            :occurrence],
    ['organismID',                          'Organism ID',                                   :organism],
    ['organismScope',                       'Organism Scope',                                :organism],
    ['organismName',                        'Organism Name',                                 :organism],
    ['causeOfDeath',                        'Cause Of Death',                                :organism],
    ['associatedOrganisms',                 'Associated Organisms',                          :organism],
    ['previousIdentifications',             'Previous Identifications',                      :organism],
    ['organismRemarks',                     'Organism Remarks',                              :organism],
    ['taxonID',                             'Taxon ID',                                      :taxon],
    ['scientificNameID',                    'Scientific Name ID',                            :taxon],
    ['acceptedNameUsageID',                 'Accepted Name Usage ID',                        :taxon],
    ['parentNameUsageID',                   'Parent Name Usage ID',                          :taxon],
    ['originalNameUsageID',                 'Original Name Usage ID',                        :taxon],
    ['nameAccordingToID',                   'Name According To ID',                          :taxon],
    ['namePublishedInID',                   'Name Published In ID',                          :taxon],
    ['taxonConceptID',                      'Taxon Concept ID',                              :taxon],
    ['scientificName',                      'Scientific Name',                               :taxon],
    ['acceptedNameUsage',                   'Accepted Name Usage',                           :taxon],
    ['parentNameUsage',                     'Parent Name Usage',                             :taxon],
    ['originalNameUsage',                   'Original Name Usage',                           :taxon],
    ['nameAccordingTo',                     'Name According To',                             :taxon],
    ['namePublishedIn',                     'Name Published In',                             :taxon],
    ['namePublishedInYear',                 'Name Published In Year',                        :taxon],
    ['higherClassification',                'Higher Classification',                         :taxon],
    ['kingdom',                             'Kingdom',                                       :taxon],
    ['phylum',                              'Phylum',                                        :taxon],
    ['class',                               'Class',                                         :taxon],
    ['order',                               'Order',                                         :taxon],
    ['superfamily',                         'Superfamily',                                   :taxon],
    ['family',                              'Family',                                        :taxon],
    ['subfamily',                           'Subfamily',                                     :taxon],
    ['tribe',                               'Tribe',                                         :taxon],
    ['subtribe',                            'Subtribe',                                      :taxon],
    ['genus',                               'Genus',                                         :taxon],
    ['genericName',                         'Generic Name',                                  :taxon],
    ['subgenus',                            'Subgenus',                                      :taxon],
    ['infragenericEpithet',                 'Infrageneric Epithet',                          :taxon],
    ['specificEpithet',                     'Specific Epithet',                              :taxon],
    ['infraspecificEpithet',                'Infraspecific Epithet',                         :taxon],
    ['cultivarEpithet',                     'Cultivar Epithet',                              :taxon],
    ['taxonRank',                           'Taxon Rank',                                    :taxon],
    ['verbatimTaxonRank',                   'Verbatim Taxon Rank',                           :taxon],
    ['scientificNameAuthorship',            'Scientific Name Authorship',                    :taxon],
    ['vernacularName',                      'Vernacular Name',                               :taxon],
    ['nomenclaturalCode',                   'Nomenclatural Code',                            :taxon],
    ['taxonomicStatus',                     'Taxonomic Status',                              :taxon],
    ['nomenclaturalStatus',                 'Nomenclatural Status',                          :taxon],
    ['taxonRemarks',                        'Taxon Remarks',                                 :taxon]
  ].freeze
end
