# Use postgres/example user/password credentials
version: '3.7'
volumes:
  db:
  storage:
services:
  db:
    image: postgres:14
    volumes:
      - db:/var/lib/postgresql/data/pgdata
    restart: always
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432
  web:
    image: nakatomi/atlas_web
    entrypoint: /home/atlas/web/docker-entrypoint.sh
    ports:
      - 3000:3000
