# frozen_string_literal: true

module MimeHelper
  def assign_classification(file_path)
    hmt = hash_mime_type(mime_type(file_path))

    classification = sub_type_check(hmt[:sub_type])
    classification = raw_type_check(hmt[:raw_type]) if classification.blank?
    classification = ext_check(file_path) if classification.blank?
    return Classification.generic if classification.blank?

    classification
  end

  def default_label(file_path)
    classification = assign_classification(file_path)
    ext = File.extname(file_path).delete_prefix('.')

    label = ext_label(ext)
    return label if label.present?

    classification_label(classification)
  end

  def ext_check(file_path)
    ext = File.extname(file_path).sub!('.', '')
    if %w[docx doc].include?(ext)
      Classification.text
    elsif %w[xls xlsx xlw].include?(ext)
      Classification.spreadsheet
    elsif %w[ppt pptx pps ppsx].include?(ext)
      Classification.presentation
    elsif %w[zip tar].include?(ext)
      Classification.archive
    end
  end

  def mime_type(file_path)
    fm = FileMagic.new(FileMagic::MAGIC_MIME_TYPE)
    fm.file(file_path)
  end

  private

    def ext_label(ext)
      case ext
      when 'doc', 'docx' then Label.msword
      when 'xls', 'xlsx', 'xlw' then Label.msexcel
      when 'ppt', 'pptx', 'pps', 'ppsx' then Label.mspowerpoint
      when 'pdf' then Label.pdf
      when 'epub' then Label.epub
      when 'csv' then Label.text
      when 'zip', 'tar' then Label.zip
      end
    end

    def classification_label(classification)
      case classification
      when Classification.image then Label.image_master
      when Classification.video then Label.video
      when Classification.audio then Label.audio
      when Classification.text then Label.text
      end
    end

    # Takes a string like "image/jpeg ; encoding=binary", generated by FileMagic.
    # And turns it into the hash {raw_type: 'image', sub_type: 'jpeg', encoding: 'binary'}
    def hash_mime_type(mime_type)
      result = {}
      result[:raw_type] = mime_type.split('/').first.strip
      result[:sub_type] = mime_type.split('/').last.strip
      result
    end

    def raw_type_check(raw_type)
      case raw_type
      when 'image'
        Classification.image
      when 'video'
        Classification.video
      when 'audio'
        Classification.audio
      when 'text'
        Classification.text
      end
    end

    def sub_type_check(sub_type)
      return Classification.text if sub_type.include?('epub') || sub_type == 'pdf' || sub_type.include?('csv')

      nil
    end
end
